### PR TITLE
bump deps

### PR DESCRIPTION
**Pull request by tunnckoCore**
update `extend-shallow`

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks! I've been out of commission for a few days, I'll be catching up on projects over the next several days.

**Comment by tunnckoCore** [comment]
@jonschlinkert yea I noticed that, welcome back! :beer:

**Comment by tunnckoCore** [comment]
@jonschlinkert and publish :)

**Comment by jonschlinkert** [comment]
still working on it!

**Comment by jonschlinkert** [comment]
done. I was thinking about making changes but I'll come back to it

**Pull request merged**
